ACTORS = {'actorface0': {'DIM': (192, 320),
                'POS': (0, 0),
                'name': 'actorface0',
                'offsetkey': 'actorface',
                'scripts': 'actorface',
                'sprites': 'actorface',
                'tangible': False},
 'actorwindow0': {'DIM': (192, 320),
                  'POS': (0, 0),
                  'name': 'actorwindow0',
                  'offsetkey': 'actorwindow',
                  'scripts': 'actorwindow',
                  'sprites': 'actorwindow',
                  'tangible': False},
 'bluebutton0': {'DIM': (128, 128),
                 'POS': (448, 160),
                 'name': 'bluebutton0',
                 'offsetkey': 'bluebutton',
                 'scripts': 'bluebutton',
                 'sprites': 'bluebutton',
                 'tangible': False},
 'letter0': {'DIM': (16, 32),
             'POS': (240, 48),
             'name': 'letter0',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter1': {'DIM': (16, 32),
             'POS': (256, 48),
             'name': 'letter1',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter10': {'DIM': (16, 32),
              'POS': (400, 48),
              'name': 'letter10',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter100': {'DIM': (16, 32),
               'POS': (400, 144),
               'name': 'letter100',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter101': {'DIM': (16, 32),
               'POS': (416, 144),
               'name': 'letter101',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter102': {'DIM': (16, 32),
               'POS': (432, 144),
               'name': 'letter102',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter103': {'DIM': (16, 32),
               'POS': (448, 144),
               'name': 'letter103',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter104': {'DIM': (16, 32),
               'POS': (464, 144),
               'name': 'letter104',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter105': {'DIM': (16, 32),
               'POS': (480, 144),
               'name': 'letter105',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter106': {'DIM': (16, 32),
               'POS': (496, 144),
               'name': 'letter106',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter107': {'DIM': (16, 32),
               'POS': (512, 144),
               'name': 'letter107',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter108': {'DIM': (16, 32),
               'POS': (528, 144),
               'name': 'letter108',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter109': {'DIM': (16, 32),
               'POS': (544, 144),
               'name': 'letter109',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter11': {'DIM': (16, 32),
              'POS': (416, 48),
              'name': 'letter11',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter110': {'DIM': (16, 32),
               'POS': (560, 144),
               'name': 'letter110',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter111': {'DIM': (16, 32),
               'POS': (576, 144),
               'name': 'letter111',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter112': {'DIM': (16, 32),
               'POS': (592, 144),
               'name': 'letter112',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter113': {'DIM': (16, 32),
               'POS': (608, 144),
               'name': 'letter113',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter114': {'DIM': (16, 32),
               'POS': (624, 144),
               'name': 'letter114',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter115': {'DIM': (16, 32),
               'POS': (640, 144),
               'name': 'letter115',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter116': {'DIM': (16, 32),
               'POS': (656, 144),
               'name': 'letter116',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter117': {'DIM': (16, 32),
               'POS': (672, 144),
               'name': 'letter117',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter118': {'DIM': (16, 32),
               'POS': (688, 144),
               'name': 'letter118',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter119': {'DIM': (16, 32),
               'POS': (704, 144),
               'name': 'letter119',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter12': {'DIM': (16, 32),
              'POS': (432, 48),
              'name': 'letter12',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter120': {'DIM': (16, 32),
               'POS': (720, 144),
               'name': 'letter120',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter121': {'DIM': (16, 32),
               'POS': (736, 144),
               'name': 'letter121',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter122': {'DIM': (16, 32),
               'POS': (752, 144),
               'name': 'letter122',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter123': {'DIM': (16, 32),
               'POS': (768, 144),
               'name': 'letter123',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter124': {'DIM': (16, 32),
               'POS': (784, 144),
               'name': 'letter124',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter125': {'DIM': (16, 32),
               'POS': (800, 144),
               'name': 'letter125',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter126': {'DIM': (16, 32),
               'POS': (816, 144),
               'name': 'letter126',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter127': {'DIM': (16, 32),
               'POS': (832, 144),
               'name': 'letter127',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter128': {'DIM': (16, 32),
               'POS': (848, 144),
               'name': 'letter128',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter129': {'DIM': (16, 32),
               'POS': (864, 144),
               'name': 'letter129',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter13': {'DIM': (16, 32),
              'POS': (448, 48),
              'name': 'letter13',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter130': {'DIM': (16, 32),
               'POS': (880, 144),
               'name': 'letter130',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter131': {'DIM': (16, 32),
               'POS': (896, 144),
               'name': 'letter131',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter132': {'DIM': (16, 32),
               'POS': (912, 144),
               'name': 'letter132',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter133': {'DIM': (16, 32),
               'POS': (928, 144),
               'name': 'letter133',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter134': {'DIM': (16, 32),
               'POS': (944, 144),
               'name': 'letter134',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter135': {'DIM': (16, 32),
               'POS': (240, 192),
               'name': 'letter135',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter136': {'DIM': (16, 32),
               'POS': (256, 192),
               'name': 'letter136',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter137': {'DIM': (16, 32),
               'POS': (272, 192),
               'name': 'letter137',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter138': {'DIM': (16, 32),
               'POS': (288, 192),
               'name': 'letter138',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter139': {'DIM': (16, 32),
               'POS': (304, 192),
               'name': 'letter139',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter14': {'DIM': (16, 32),
              'POS': (464, 48),
              'name': 'letter14',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter140': {'DIM': (16, 32),
               'POS': (320, 192),
               'name': 'letter140',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter141': {'DIM': (16, 32),
               'POS': (336, 192),
               'name': 'letter141',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter142': {'DIM': (16, 32),
               'POS': (352, 192),
               'name': 'letter142',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter143': {'DIM': (16, 32),
               'POS': (368, 192),
               'name': 'letter143',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter144': {'DIM': (16, 32),
               'POS': (384, 192),
               'name': 'letter144',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter145': {'DIM': (16, 32),
               'POS': (400, 192),
               'name': 'letter145',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter146': {'DIM': (16, 32),
               'POS': (416, 192),
               'name': 'letter146',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter147': {'DIM': (16, 32),
               'POS': (432, 192),
               'name': 'letter147',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter148': {'DIM': (16, 32),
               'POS': (448, 192),
               'name': 'letter148',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter149': {'DIM': (16, 32),
               'POS': (464, 192),
               'name': 'letter149',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter15': {'DIM': (16, 32),
              'POS': (480, 48),
              'name': 'letter15',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter150': {'DIM': (16, 32),
               'POS': (480, 192),
               'name': 'letter150',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter151': {'DIM': (16, 32),
               'POS': (496, 192),
               'name': 'letter151',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter152': {'DIM': (16, 32),
               'POS': (512, 192),
               'name': 'letter152',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter153': {'DIM': (16, 32),
               'POS': (528, 192),
               'name': 'letter153',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter154': {'DIM': (16, 32),
               'POS': (544, 192),
               'name': 'letter154',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter155': {'DIM': (16, 16),
               'POS': (560, 192),
               'name': 'letter155',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter156': {'DIM': (16, 32),
               'POS': (576, 192),
               'name': 'letter156',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter157': {'DIM': (16, 32),
               'POS': (592, 192),
               'name': 'letter157',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter158': {'DIM': (16, 32),
               'POS': (608, 192),
               'name': 'letter158',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter159': {'DIM': (16, 32),
               'POS': (624, 192),
               'name': 'letter159',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter16': {'DIM': (16, 32),
              'POS': (496, 48),
              'name': 'letter16',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter160': {'DIM': (16, 32),
               'POS': (640, 192),
               'name': 'letter160',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter161': {'DIM': (16, 32),
               'POS': (656, 192),
               'name': 'letter161',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter162': {'DIM': (16, 32),
               'POS': (672, 192),
               'name': 'letter162',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter163': {'DIM': (16, 32),
               'POS': (688, 192),
               'name': 'letter163',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter164': {'DIM': (16, 32),
               'POS': (704, 192),
               'name': 'letter164',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter165': {'DIM': (16, 32),
               'POS': (720, 192),
               'name': 'letter165',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter166': {'DIM': (16, 32),
               'POS': (736, 192),
               'name': 'letter166',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter167': {'DIM': (16, 32),
               'POS': (752, 192),
               'name': 'letter167',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter168': {'DIM': (16, 32),
               'POS': (768, 192),
               'name': 'letter168',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter169': {'DIM': (16, 32),
               'POS': (784, 192),
               'name': 'letter169',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter17': {'DIM': (16, 32),
              'POS': (512, 48),
              'name': 'letter17',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter170': {'DIM': (16, 32),
               'POS': (800, 192),
               'name': 'letter170',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter171': {'DIM': (16, 32),
               'POS': (816, 192),
               'name': 'letter171',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter172': {'DIM': (16, 32),
               'POS': (832, 192),
               'name': 'letter172',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter173': {'DIM': (16, 32),
               'POS': (848, 192),
               'name': 'letter173',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter174': {'DIM': (16, 32),
               'POS': (864, 192),
               'name': 'letter174',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter175': {'DIM': (16, 32),
               'POS': (880, 192),
               'name': 'letter175',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter176': {'DIM': (16, 32),
               'POS': (896, 192),
               'name': 'letter176',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter177': {'DIM': (16, 32),
               'POS': (912, 192),
               'name': 'letter177',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter178': {'DIM': (16, 32),
               'POS': (928, 192),
               'name': 'letter178',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter179': {'DIM': (16, 32),
               'POS': (944, 192),
               'name': 'letter179',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter18': {'DIM': (16, 32),
              'POS': (528, 48),
              'name': 'letter18',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter180': {'DIM': (16, 32),
               'POS': (240, 240),
               'name': 'letter180',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter181': {'DIM': (16, 32),
               'POS': (256, 240),
               'name': 'letter181',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter182': {'DIM': (16, 32),
               'POS': (272, 240),
               'name': 'letter182',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter183': {'DIM': (16, 32),
               'POS': (288, 240),
               'name': 'letter183',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter184': {'DIM': (16, 32),
               'POS': (304, 240),
               'name': 'letter184',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter185': {'DIM': (16, 32),
               'POS': (320, 240),
               'name': 'letter185',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter186': {'DIM': (16, 32),
               'POS': (336, 240),
               'name': 'letter186',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter187': {'DIM': (16, 32),
               'POS': (352, 240),
               'name': 'letter187',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter188': {'DIM': (16, 32),
               'POS': (368, 240),
               'name': 'letter188',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter189': {'DIM': (16, 32),
               'POS': (384, 240),
               'name': 'letter189',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter19': {'DIM': (16, 32),
              'POS': (544, 48),
              'name': 'letter19',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter190': {'DIM': (16, 32),
               'POS': (400, 240),
               'name': 'letter190',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter191': {'DIM': (16, 32),
               'POS': (416, 240),
               'name': 'letter191',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter192': {'DIM': (16, 32),
               'POS': (432, 240),
               'name': 'letter192',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter193': {'DIM': (16, 32),
               'POS': (448, 240),
               'name': 'letter193',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter194': {'DIM': (16, 32),
               'POS': (464, 240),
               'name': 'letter194',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter195': {'DIM': (16, 32),
               'POS': (480, 240),
               'name': 'letter195',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter196': {'DIM': (16, 32),
               'POS': (496, 240),
               'name': 'letter196',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter197': {'DIM': (16, 32),
               'POS': (512, 240),
               'name': 'letter197',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter198': {'DIM': (16, 32),
               'POS': (528, 240),
               'name': 'letter198',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter199': {'DIM': (16, 32),
               'POS': (544, 240),
               'name': 'letter199',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter2': {'DIM': (16, 32),
             'POS': (272, 48),
             'name': 'letter2',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter20': {'DIM': (16, 32),
              'POS': (560, 48),
              'name': 'letter20',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter200': {'DIM': (16, 32),
               'POS': (560, 240),
               'name': 'letter200',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter201': {'DIM': (16, 32),
               'POS': (576, 240),
               'name': 'letter201',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter202': {'DIM': (16, 32),
               'POS': (592, 240),
               'name': 'letter202',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter203': {'DIM': (16, 32),
               'POS': (608, 240),
               'name': 'letter203',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter204': {'DIM': (16, 32),
               'POS': (624, 240),
               'name': 'letter204',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter205': {'DIM': (16, 32),
               'POS': (640, 240),
               'name': 'letter205',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter206': {'DIM': (16, 32),
               'POS': (656, 240),
               'name': 'letter206',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter207': {'DIM': (16, 32),
               'POS': (672, 240),
               'name': 'letter207',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter208': {'DIM': (16, 32),
               'POS': (688, 240),
               'name': 'letter208',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter209': {'DIM': (16, 32),
               'POS': (704, 240),
               'name': 'letter209',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter21': {'DIM': (16, 32),
              'POS': (576, 48),
              'name': 'letter21',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter210': {'DIM': (16, 32),
               'POS': (720, 240),
               'name': 'letter210',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter211': {'DIM': (16, 32),
               'POS': (736, 240),
               'name': 'letter211',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter212': {'DIM': (16, 32),
               'POS': (752, 240),
               'name': 'letter212',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter213': {'DIM': (16, 32),
               'POS': (768, 240),
               'name': 'letter213',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter214': {'DIM': (16, 32),
               'POS': (784, 240),
               'name': 'letter214',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter215': {'DIM': (16, 32),
               'POS': (800, 240),
               'name': 'letter215',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter216': {'DIM': (16, 32),
               'POS': (816, 240),
               'name': 'letter216',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter217': {'DIM': (16, 32),
               'POS': (832, 240),
               'name': 'letter217',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter218': {'DIM': (16, 32),
               'POS': (848, 240),
               'name': 'letter218',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter219': {'DIM': (16, 32),
               'POS': (864, 240),
               'name': 'letter219',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter22': {'DIM': (16, 32),
              'POS': (592, 48),
              'name': 'letter22',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter220': {'DIM': (16, 32),
               'POS': (880, 240),
               'name': 'letter220',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter221': {'DIM': (16, 32),
               'POS': (896, 240),
               'name': 'letter221',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter222': {'DIM': (16, 32),
               'POS': (912, 240),
               'name': 'letter222',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter223': {'DIM': (16, 32),
               'POS': (928, 240),
               'name': 'letter223',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter224': {'DIM': (16, 32),
               'POS': (944, 240),
               'name': 'letter224',
               'offsetkey': 'letter',
               'scripts': 'letter',
               'sprites': 'letter',
               'tangible': False},
 'letter23': {'DIM': (16, 32),
              'POS': (608, 48),
              'name': 'letter23',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter24': {'DIM': (16, 32),
              'POS': (624, 48),
              'name': 'letter24',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter25': {'DIM': (16, 32),
              'POS': (640, 48),
              'name': 'letter25',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter26': {'DIM': (16, 32),
              'POS': (656, 48),
              'name': 'letter26',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter27': {'DIM': (16, 32),
              'POS': (672, 48),
              'name': 'letter27',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter28': {'DIM': (16, 32),
              'POS': (688, 48),
              'name': 'letter28',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter29': {'DIM': (16, 32),
              'POS': (704, 48),
              'name': 'letter29',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter3': {'DIM': (16, 32),
             'POS': (288, 48),
             'name': 'letter3',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter30': {'DIM': (16, 32),
              'POS': (720, 48),
              'name': 'letter30',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter31': {'DIM': (16, 32),
              'POS': (736, 48),
              'name': 'letter31',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter32': {'DIM': (16, 32),
              'POS': (752, 48),
              'name': 'letter32',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter33': {'DIM': (16, 32),
              'POS': (768, 48),
              'name': 'letter33',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter34': {'DIM': (16, 32),
              'POS': (784, 48),
              'name': 'letter34',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter35': {'DIM': (16, 32),
              'POS': (800, 48),
              'name': 'letter35',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter36': {'DIM': (16, 32),
              'POS': (816, 48),
              'name': 'letter36',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter37': {'DIM': (16, 32),
              'POS': (832, 48),
              'name': 'letter37',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter38': {'DIM': (16, 32),
              'POS': (848, 48),
              'name': 'letter38',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter39': {'DIM': (16, 32),
              'POS': (864, 48),
              'name': 'letter39',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter4': {'DIM': (16, 32),
             'POS': (304, 48),
             'name': 'letter4',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter40': {'DIM': (16, 32),
              'POS': (880, 48),
              'name': 'letter40',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter41': {'DIM': (16, 32),
              'POS': (896, 48),
              'name': 'letter41',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter42': {'DIM': (16, 32),
              'POS': (912, 48),
              'name': 'letter42',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter43': {'DIM': (16, 32),
              'POS': (928, 48),
              'name': 'letter43',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter44': {'DIM': (16, 32),
              'POS': (944, 48),
              'name': 'letter44',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter45': {'DIM': (16, 32),
              'POS': (240, 96),
              'name': 'letter45',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter46': {'DIM': (16, 32),
              'POS': (256, 96),
              'name': 'letter46',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter47': {'DIM': (16, 32),
              'POS': (272, 96),
              'name': 'letter47',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter48': {'DIM': (16, 32),
              'POS': (288, 96),
              'name': 'letter48',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter49': {'DIM': (16, 32),
              'POS': (304, 96),
              'name': 'letter49',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter5': {'DIM': (16, 32),
             'POS': (320, 48),
             'name': 'letter5',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter50': {'DIM': (16, 32),
              'POS': (320, 96),
              'name': 'letter50',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter51': {'DIM': (16, 32),
              'POS': (336, 96),
              'name': 'letter51',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter52': {'DIM': (16, 32),
              'POS': (352, 96),
              'name': 'letter52',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter53': {'DIM': (16, 32),
              'POS': (368, 96),
              'name': 'letter53',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter54': {'DIM': (16, 32),
              'POS': (384, 96),
              'name': 'letter54',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter55': {'DIM': (16, 32),
              'POS': (400, 96),
              'name': 'letter55',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter56': {'DIM': (16, 32),
              'POS': (416, 96),
              'name': 'letter56',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter57': {'DIM': (16, 32),
              'POS': (432, 96),
              'name': 'letter57',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter58': {'DIM': (16, 32),
              'POS': (448, 96),
              'name': 'letter58',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter59': {'DIM': (16, 32),
              'POS': (464, 96),
              'name': 'letter59',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter6': {'DIM': (16, 32),
             'POS': (336, 48),
             'name': 'letter6',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter60': {'DIM': (16, 32),
              'POS': (480, 96),
              'name': 'letter60',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter61': {'DIM': (16, 32),
              'POS': (496, 96),
              'name': 'letter61',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter62': {'DIM': (16, 32),
              'POS': (512, 96),
              'name': 'letter62',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter63': {'DIM': (16, 32),
              'POS': (528, 96),
              'name': 'letter63',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter64': {'DIM': (16, 32),
              'POS': (544, 96),
              'name': 'letter64',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter65': {'DIM': (16, 32),
              'POS': (560, 96),
              'name': 'letter65',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter66': {'DIM': (16, 32),
              'POS': (576, 96),
              'name': 'letter66',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter67': {'DIM': (16, 32),
              'POS': (592, 96),
              'name': 'letter67',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter68': {'DIM': (16, 32),
              'POS': (608, 96),
              'name': 'letter68',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter69': {'DIM': (16, 32),
              'POS': (624, 96),
              'name': 'letter69',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter7': {'DIM': (16, 32),
             'POS': (352, 48),
             'name': 'letter7',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter70': {'DIM': (16, 32),
              'POS': (640, 96),
              'name': 'letter70',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter71': {'DIM': (16, 32),
              'POS': (656, 96),
              'name': 'letter71',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter72': {'DIM': (16, 32),
              'POS': (672, 96),
              'name': 'letter72',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter73': {'DIM': (16, 32),
              'POS': (688, 96),
              'name': 'letter73',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter74': {'DIM': (16, 32),
              'POS': (704, 96),
              'name': 'letter74',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter75': {'DIM': (16, 32),
              'POS': (720, 96),
              'name': 'letter75',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter76': {'DIM': (16, 32),
              'POS': (736, 96),
              'name': 'letter76',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter77': {'DIM': (16, 32),
              'POS': (752, 96),
              'name': 'letter77',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter78': {'DIM': (16, 32),
              'POS': (768, 96),
              'name': 'letter78',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter79': {'DIM': (16, 32),
              'POS': (784, 96),
              'name': 'letter79',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter8': {'DIM': (16, 32),
             'POS': (368, 48),
             'name': 'letter8',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter80': {'DIM': (16, 32),
              'POS': (800, 96),
              'name': 'letter80',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter81': {'DIM': (16, 32),
              'POS': (816, 96),
              'name': 'letter81',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter82': {'DIM': (16, 32),
              'POS': (832, 96),
              'name': 'letter82',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter83': {'DIM': (16, 32),
              'POS': (848, 96),
              'name': 'letter83',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter84': {'DIM': (16, 32),
              'POS': (864, 96),
              'name': 'letter84',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter85': {'DIM': (16, 32),
              'POS': (880, 96),
              'name': 'letter85',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter86': {'DIM': (16, 32),
              'POS': (896, 96),
              'name': 'letter86',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter87': {'DIM': (16, 32),
              'POS': (912, 96),
              'name': 'letter87',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter88': {'DIM': (16, 32),
              'POS': (928, 96),
              'name': 'letter88',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter89': {'DIM': (16, 32),
              'POS': (944, 96),
              'name': 'letter89',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter9': {'DIM': (16, 32),
             'POS': (384, 48),
             'name': 'letter9',
             'offsetkey': 'letter',
             'scripts': 'letter',
             'sprites': 'letter',
             'tangible': False},
 'letter90': {'DIM': (16, 32),
              'POS': (240, 144),
              'name': 'letter90',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter91': {'DIM': (16, 32),
              'POS': (256, 144),
              'name': 'letter91',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter92': {'DIM': (16, 32),
              'POS': (272, 144),
              'name': 'letter92',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter93': {'DIM': (16, 32),
              'POS': (288, 144),
              'name': 'letter93',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter94': {'DIM': (16, 32),
              'POS': (304, 144),
              'name': 'letter94',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter95': {'DIM': (16, 32),
              'POS': (320, 144),
              'name': 'letter95',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter96': {'DIM': (16, 32),
              'POS': (336, 144),
              'name': 'letter96',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter97': {'DIM': (16, 32),
              'POS': (352, 144),
              'name': 'letter97',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter98': {'DIM': (16, 32),
              'POS': (368, 144),
              'name': 'letter98',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'letter99': {'DIM': (16, 32),
              'POS': (384, 144),
              'name': 'letter99',
              'offsetkey': 'letter',
              'scripts': 'letter',
              'sprites': 'letter',
              'tangible': False},
 'mouseCover0': {'DIM': (48, 48),
                 'POS': (192, 208),
                 'name': 'mouseCover0',
                 'offsetkey': 'mouseCover',
                 'scripts': 'mouseCover',
                 'sprites': 'mouseCover',
                 'tangible': False},
 'redbutton0': {'DIM': (128, 128),
                'POS': (96, 160),
                'name': 'redbutton0',
                'offsetkey': 'redbutton',
                'scripts': 'redbutton',
                'sprites': 'redbutton',
                'tangible': False},
 'saybubble0': {'DIM': (832, 320),
                'POS': (192, 0),
                'name': 'saybubble0',
                'offsetkey': 'saybubble',
                'scripts': 'saybubble',
                'sprites': 'saybubble',
                'tangible': False},
 'saymaster0': {'DIM': (16, 16),
                'POS': (-64, -32),
                'name': 'saymaster0',
                'offsetkey': 'saymaster',
                'scripts': 'saymaster',
                'sprites': 'saymaster',
                'tangible': False},
 'theman0': {'DIM': (192, 320),
             'POS': (752, 144),
             'name': 'theman0',
             'offsetkey': 'theman',
             'scripts': 'theman',
             'sprites': 'theman',
             'tangible': False}}