SCRIPTS = {'actorface': {'START:0': [['set', 'self', 'state', 'OFF']]},
 'actorwindow': {},
 'bluebutton': {'OFF:0': [['if', 'MOUSEOVER?'],
                          ['set', 'self', 'state', 'OVER'],
                          ['endif']],
                'OVER:0': [['if', 'not', 'MOUSEOVER?'],
                           ['set', 'self', 'state', 'OFF'],
                           ['break'],
                           ['endif'],
                           ['if', 'inpCLICK_LEFT'],
                           ['set', 'self', 'state', 'PRESSED'],
                           ['exec', 'press'],
                           ['endif']],
                'PRESSED:0': [['if', 'not', 'MOUSEOVER?'],
                              ['set', 'self', 'state', 'OFF'],
                              ['endif'],
                              ['if', 'not', 'inpMOUSE_LEFT'],
                              ['set', 'self', 'state', 'OVER'],
                              ['endif']],
                'START:0': [['set', 'self', 'state', 'OFF'],
                            ['set', 'self', 'platform', '1']],
                'press': [['set', 'self', 'calc', 'isframe', 'SAY'],
                          ['if', 'not', 'self.calc'],
                          ['makeframe',
                           'SAY',
                           'sayroom',
                           '64',
                           '256',
                           '1024',
                           '320'],
                          ['endif'],
                          ['set', 'actorface0', 'state', 'TEST_MAN_WHAT'],
                          ['set', 'saymaster0', 'state', 'UPDATEALL'],
                          ['set', 'saymaster0', 'AT', '0'],
                          ['set',
                           'saymaster0',
                           'text',
                           'GRRR IM SO MAD! I CANNOT BELIEVE YOU WOULD BE SUCH '
                           'A FREAKING JERK! GAH IM SO MAD I COULD PUNCH YOU '
                           'IN THE STUPID HEAD! GRR HOW COULD YOU BE SO '
                           'STUPID??']]},
 'hud_seperator': {'START:0': []},
 'hud_seperator_inv': {'START:0': [['set', 'self', 'platform', '1'],
                                   ['set', 'self', 'state', 'INV']]},
 'hud_seperator_off': {'START:0': [['back'],
                                   ['set', 'self', 'platform', '1'],
                                   ['set', 'self', 'state', 'OFF'],
                                   ['set', 'self', 'w', 'self.w', '-', '16'],
                                   ['set', 'self', 'h', 'self.h', '-', '16']]},
 'hud_seperator_on': {'START:0': [['set', 'self', 'platform', '1'],
                                  ['set', 'self', 'state', 'ON']]},
 'letter': {'START:0': [['set', 'self', 'direction', '-1'],
                        ['set', 'self', 'state', '_SPACE_']]},
 'mouseCover': {'CLOSED:0': [['set', 'self', 'x', 'inpMOUSE_X'],
                             ['set', 'self', 'y', 'inpMOUSE_Y'],
                             ['if', 'not', 'inpMOUSE_LEFT'],
                             ['set', 'self', 'state', 'POINT'],
                             ['endif']],
                'POINT:0': [['set', 'self', 'x', 'inpMOUSE_X'],
                            ['set', 'self', 'y', 'inpMOUSE_Y'],
                            ['if', 'inpMOUSE_LEFT'],
                            ['set', 'self', 'state', 'CLOSED'],
                            ['endif']],
                'START:0': [['set', 'self', 'direction', '-1'],
                            ['show_mouse', '0'],
                            ['set', 'self', 'state', 'POINT']]},
 'mousetester': {'START:0': [['print',
                              'inpMOUSE_X',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_Y'],
                             ['print',
                              'inpMOUSE_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_RIGHT'],
                             ['print',
                              'inpCLICK_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpCLICK_RIGHT'],
                             ['if', 'MOUSEOVER?'],
                             ['print', 'MOUSE OVER!'],
                             ['endif']]},
 'redbutton': {'OFF:0': [['if', 'MOUSEOVER?'],
                         ['set', 'self', 'state', 'OVER'],
                         ['endif']],
               'OVER:0': [['if', 'not', 'MOUSEOVER?'],
                          ['set', 'self', 'state', 'OFF'],
                          ['break'],
                          ['endif'],
                          ['if', 'inpCLICK_LEFT'],
                          ['set', 'self', 'state', 'PRESSED'],
                          ['exec', 'press'],
                          ['endif']],
               'PRESSED:0': [['if', 'not', 'MOUSEOVER?'],
                             ['set', 'self', 'state', 'OFF'],
                             ['endif'],
                             ['if', 'not', 'inpMOUSE_LEFT'],
                             ['set', 'self', 'state', 'OVER'],
                             ['endif']],
               'START:0': [['set', 'self', 'state', 'OFF'],
                           ['set', 'self', 'platform', '1']],
               'press': [['set', 'self', 'calc', 'isframe', 'SAY'],
                         ['if', 'not', 'self.calc'],
                         ['makeframe',
                          'SAY',
                          'sayroom',
                          '64',
                          '256',
                          '1024',
                          '320'],
                         ['endif'],
                         ['set', 'actorface0', 'state', 'TEST_MAN_HEY'],
                         ['set', 'saymaster0', 'state', 'UPDATEALL'],
                         ['set', 'saymaster0', 'AT', '0'],
                         ['set',
                          'saymaster0',
                          'text',
                          'GREAT! NOW DO IT AGAIN AND AGAIN AND AGAIN!!!']]},
 'saybubble': {'START:0': [['set', 'self', 'direction', '-1'],
                           ['set', 'self', 'state', 'WAIT']]},
 'saymaster': {'START:0': [['set', 'self', 'state', 'WAIT'],
                           ['set', 'self', 'letters', '224'],
                           ['set', 'self', 'per_line', '45'],
                           ['set', 'self', 'AT', '0'],
                           ['set',
                            'self',
                            '_text',
                            'THIS IS THE DEFAULT TEXT LOADED IN MEMORY THAT '
                            'THE TEXT WILL SAY IF IT IS SOMEHOW NOT BEING '
                            'INITIALIZED ELSEWHERE IN THE APPLICATION, IM '
                            'TERRIBLY SORRY@ IM GOING TO KEEP TYPING THOUGH '
                            'BECAUSE IT COULD BE USEFUL FOR DEBUG PURPOSES FOR '
                            'ME TO TEST THE TEXT, SO I GUESS AT THIS POINT ITS '
                            'REALLY JUST FLAVOR TEXT PRETTY AWESOME, EH? WOULD '
                            'YOU LIKE TO KNOW HOW MY DAY WAS? IT WAS OKAY@ I '
                            'DONT HAVE A JOB AND SO I BASICALLY JUST DID THIS '
                            'ALL DAY@ HEY DONT TELL ME WHAT TO DO, I AUGHTA, '
                            'WHY I AUGHTA GRRR I WONT LET YOU GET AWAY WITH '
                            'THIS! IM GONNA GETCHA IM GONNA GETCHA! OH WAIT I '
                            'DONT THINK I CAN GET YOU BECAUSE IM JUST SITTING '
                            'HERE TYPING AND YOUR ON THE OTHER SIDE, THAT IS '
                            'TO SAY YOURE PLAYING THIS IN THE FUTURE BECAUSE '
                            'AS IM TYPING THIS THE GAME IS NOT DONE YET@ '
                            'ANYWAYS THATS PROBABLY ENOUGH TEXT TO SCROLL FOR '
                            'A WHILE, THANK YOU SO MUCH FOR PLAYING MY GAME@'],
                           ['set', 'self', 'text', 'self._text']],
               'UPDATEALL:0': [['exec', 'updateText'],
                               ['set', 'self', 'frame', '0'],
                               ['set', 'self', 'state', 'WAIT']],
               'WAIT:2': [['if', 'inpCLICK_LEFT'],
                          ['if', 'isframe', 'SAY'],
                          ['killframe', 'SAY'],
                          ['endif'],
                          ['endif']],
               'updateText': [['for', 'letterIdx', 'range', 'self.letters'],
                              ['set',
                               'self',
                               'lettername',
                               'letter',
                               '+',
                               'letterIdx'],
                              ['if', 'len', 'self.text', '<=', 'self.AT'],
                              ['set', 'self.lettername', 'state', '_SPACE_'],
                              ['break'],
                              ['endif'],
                              ['set',
                               'self.lettername',
                               'state',
                               'self.text',
                               'at',
                               'self.AT'],
                              ['if', 'self.lettername.state', '==', ' '],
                              ['set', 'self.lettername', 'state', '_SPACE_'],
                              ['endif'],
                              ['if', 'self.lettername.state', '==', '@'],
                              ['set', 'self.lettername', 'state', 'DOT'],
                              ['endif'],
                              ['if', 'self.lettername.state', '==', ','],
                              ['set', 'self.lettername', 'state', 'COMMA'],
                              ['endif'],
                              ['if', 'self.lettername.state', '==', '?'],
                              ['set', 'self.lettername', 'state', 'QUESTION'],
                              ['endif'],
                              ['if', 'self.lettername.state', '==', '!'],
                              ['set', 'self.lettername', 'state', 'BANG'],
                              ['endif'],
                              ['set', 'self', 'AT', 'self.AT', '+', '1'],
                              ['endfor']]},
 'theman': {'OVER:0': [['if', 'not', 'MOUSEOVER?'],
                       ['set', 'self', 'state', 'WAIT'],
                       ['endif'],
                       ['if', 'inpCLICK_LEFT'],
                       ['exec', 'press'],
                       ['set', 'self', 'state', 'WAIT'],
                       ['endif']],
            'START:0': [['set', 'self', 'state', 'WAIT']],
            'WAIT:0': [['if', 'MOUSEOVER?'],
                       ['set', 'self', 'state', 'OVER'],
                       ['endif']],
            'press': [['set', 'self', 'calc', 'isframe', 'SAY'],
                      ['if', 'not', 'self.calc'],
                      ['makeframe',
                       'SAY',
                       'sayroom',
                       '64',
                       '256',
                       '1024',
                       '320'],
                      ['endif'],
                      ['set', 'actorface0', 'state', 'TEST_MAN_HEY'],
                      ['set', 'saymaster0', 'state', 'UPDATEALL'],
                      ['set', 'saymaster0', 'AT', '0'],
                      ['set',
                       'saymaster0',
                       'text',
                       ' YOU BETTER PUSH THAT RED BUTTON!']]}}