SCRIPTS = {'mousetester': {'START:0': [['print',
                              'inpMOUSE_X',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_Y'],
                             ['print',
                              'inpMOUSE_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_RIGHT'],
                             ['print',
                              'inpCLICK_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpCLICK_RIGHT'],
                             ['if', 'MOUSEOVER?'],
                             ['print', 'MOUSE OVER!'],
                             ['endif']]}}