SCRIPTS = {'mouseCover': {'CLOSED:0': [['set', 'self', 'x', 'inpMOUSE_X'],
                             ['set', 'self', 'y', 'inpMOUSE_Y'],
                             ['if', 'not', 'inpMOUSE_LEFT'],
                             ['set', 'self', 'state', 'POINT'],
                             ['endif']],
                'POINT:0': [['set', 'self', 'x', 'inpMOUSE_X'],
                            ['set', 'self', 'y', 'inpMOUSE_Y'],
                            ['if', 'inpMOUSE_LEFT'],
                            ['set', 'self', 'state', 'CLOSED'],
                            ['endif']],
                'START:0': [['set', 'self', 'direction', '-1'],
                            ['show_mouse', '0'],
                            ['set', 'self', 'state', 'POINT']]},
 'mousetester': {'START:0': [['print',
                              'inpMOUSE_X',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_Y'],
                             ['print',
                              'inpMOUSE_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpMOUSE_RIGHT'],
                             ['print',
                              'inpCLICK_LEFT',
                              '+',
                              ', ',
                              '+',
                              'inpCLICK_RIGHT'],
                             ['if', 'MOUSEOVER?'],
                             ['print', 'MOUSE OVER!'],
                             ['endif']]}}