
// The following code was generated by the Red Pants Engine
// lets go baby

#include "imagedata.h"
#include "sprites.h"
#include <SDL2/SDL.h>

void spritesheet_load(SDL_Renderer* rend) {
    load_sprite(34, _background, 16, 16, rend);
    load_sprite(37, _empty, 16, 32, rend);
    load_sprite(65, _white, 64, 64, rend);
    load_sprite(50, _mousehand0, 48, 48, rend);
    load_sprite(51, _mousehand1, 48, 48, rend);
    add_offset(50, -8, -8);
    add_offset(51, -8, -8);
    add_sprite_map(48);
    add_to_sprite_map(48, 22, 0, 50);
    add_to_sprite_map(48, 18, 0, 50);
    add_to_sprite_map(48, 8, 0, 51);
    add_sprite_map(52);
}
