
// The following code was generated by the Red Pants Engine
// lets go baby

#include "imagedata.h"
#include "sprites.h"
#include <SDL2/SDL.h>

void spritesheet_load(SDL_Renderer* rend) {
    load_sprite(32, _background, 16, 16, rend);
    load_sprite(35, _empty, 16, 32, rend);
    load_sprite(60, _white, 64, 64, rend);
    add_sprite_map(46);
}
